$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

conda_file: conda_dependencies.yml
description: Custom environment for AI Training
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
name: diabetes-prediction-env-training
os_type: linux
version: 2
tags:
  git-sha: 1234567890abcdef
  git-branch: main