replicaCount: 1

api:
  name: diabetes-prediction-api
  version: v1

image:
  repository: docker.io/bartdewa/diabetes-prediction
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8090
  targetPort: 80
  nodePort: 30012

randomname: default-name