replicaCount: 1

image:
  repository: docker.io/bartdewa/diabetes-prediction
  tag: sha-4ddb715
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8090
  targetPort: 80
  nodePort: 30033

randomname: default-name