name: MLOps Automation

on:
  push:
    branches: [ master ]
 
jobs:
  start:
    uses: ./.github/workflows/azure-ai.yml
    with:
      data_prep: true
      ai_training: true
      api_creation: true
      api_deployment: true
    secrets: inherit