name: MLOps Automation

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
 
jobs:
  start:
    uses: ./.github/workflows/azure-ml-sdk1.yml
    with:
      data_prep: false
      ai_training: false
      api_creation: true
      api_deployment: true
    secrets: inherit