# This is a basic workflow to help you get started with Actions

name: MLOps test

# Controls when the workflow will run
on:
  workflow_dispatch:
   
  
env:
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

  WORKDIR: ${{ github.workspace }}
  GIT_SHA: ${{ github.sha }} # Set the SHA to use in the code

  AZ_CLI_PATH: ${{ github.workspace }}/azureml-2.0-cli
  AZ_WORKSPACE: diabetes-prediction-v2
  
jobs:

  data-check:
    runs-on: ubuntu-20.04

    env:
      ENV_VERSION: 1.0.0
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: add extension by name
        run: az extension add --name ml

      - name: azure login  
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      
      - name: set default workspace
        continue-on-error: true  
        run: az configure --defaults group=mlops-bart workspace=${{ env.AZ_WORKSPACE }}
        
      - name: create environment
        continue-on-error: true  
        run: az ml environment create --file ${{ env.AZ_CLI_PATH }}/config/diabetes-prediction-env.yml
                                      --version ${{ env.ENV_VERSION }}
                                      --set tags.git-sha=${{ env.GIT_SHA }}
