# This is a basic workflow to help you get started with Actions

name: MLOps test

# Controls when the workflow will run
on:
  workflow_dispatch:
   
  
env:
  WORKDIR: ${{github.workspace}}
  GIT_SHA: ${{ github.sha }} # Set the SHA to use in the code
  
jobs:

  data-preparing:
    runs-on: ubuntu-20.04 # Because of issues with dotnet, we downgraded this one
   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create environment
        continue-on-error: true  
        run: az configure --defaults group=mlops-bart workspace=diabetes-prediction-v2




