name: Test azure login

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
   
jobs:

  az-pipeline-job:
    runs-on: ubuntu-20.04

    steps:
      - name: azure login  
        run: |
             az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
             az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
                az account show
                az storage -h

                              

