name: Test azure login

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
   
jobs:

  az-pipeline-job:
    runs-on: ubuntu-20.04

    env:
      WORKDIR: ${{ github.workspace }}
      GIT_SHA: ${{ github.sha }} # Set the SHA to use in the code

      AZ_CLI_PATH: ${{ github.workspace }}/azureml-2.0-cli
      
      RANDOM_SEED: 40
      TRAIN_TEST_SPLIT_FACTOR: 0.20
      TRAIN_DATASHEET_NAME: patients_healthdata_1_train.csv
      TEST_DATASHEET_NAME: patients_healthdata_1_test.csv
      MODEL_NAME: diabetes-prediction-model
      DATA_CHECK_VERSION: 1.0.3
      DATA_SPLIT_VERSION: 1.0.3
      TRAIN_VERSION: 2.0.9

    steps:
      - name: azure login  
        run: |
             az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
             az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
                az extension add --name ml 
                az ml job create --file ${{ env.AZ_CLI_PATH }}/pipelines/prediction-pipeline.yml
                  --set inputs.random_seed=${{ env.RANDOM_SEED }}
                  --set inputs.train_test_split_factor=${{ env.TRAIN_TEST_SPLIT_FACTOR }}
                  --set jobs.data_check.component=azureml:data_check:${{ env.DATA_CHECK_VERSION }}
                  --set jobs.data_split.component=azureml:data_split:${{ env.DATA_SPLIT_VERSION }}
                  --set jobs.training.component=azureml:training:${{ env.TRAIN_VERSION }}


                              

