name: Test azure login

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
   
jobs:

  az-pipeline-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
            pwd

                              

